### ISSUE TITLE
Why hash and salt are both optional?

### ISSUE THREAD

**Issue by simonepri** [P-H-C/phc-string-format#3]
This page has discrepancies with this post:
http://lists.openwall.net/phc-discussions/2015/09/13/4

**Comment by tarcieri** [comment]
The discussion about making hash and salt optional is later in the thread:

https://lists.openwall.net/phc-discussions/2015/09/14/3

> It should be possible to create a string free of both salt and hash. This could be used for passing around configuration parameters in some circumstances.

I believe the idea is you can use such a string to specify an algorithm and its configuration parameters without making it represent a specific hash.

**Comment by tarcieri** [comment]
Closing per my previous response

**Comment by zefr0x** [comment]
Why we can't have optional salt separate from the hash?

By `$<id>[$v=<version>][$<param>=<value>(,<param>=<value>)*][$<salt>[$<hash>]]`, we can't have a hash without a salt, but we can have a salt without a hash.

In some cases where the password is not user input we might not need a salt (e.g. random session tokens).

As a workaround, we can supply the hash as a salt, but this will only work for some implementation.

**Comment by tarcieri** [comment]
This format, and the "Modular Crypt Format" in general, uses either optional interstitial fields/segments that start with a leading prefix (e.g. `v=`) which means they can be clearly disambiguated, or untagged fields which can be optional and have a fixed order, thus that their optionality goes right-to-left in sequence.

I'm not aware of any precedent for an unprefixed interstitial optional segment in any MCF-alike format, and it's unclear how such a segment would be disambiguated, especially since both `$salt` and `$hash` can be variable length.
